env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:functional/recommended
  - plugin:react-hooks/recommended
  - react-app

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - functional

rules:
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  react/react-in-jsx-scope: 0
  functional/no-conditional-statements: off
  functional/no-expression-statement: off
  functional/immutable-data: off
  functional/functional-parameters: off
  functional/no-try-statement: off
  functional/no-throw-statement: off
  functional/no-expression-statements: off
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  react/function-component-definition:
    [2, { 'namedComponents': 'arrow-function' }]
  testing-library/no-debug: off
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }]
  functional/no-return-void: off #*
  import/no-anonymous-default-export: 0 #*
  no-param-reassign: 0 #*
  react-hooks/exhaustive-deps: 0 #*
